const swaggerJsdoc = require('swagger-jsdoc')

const options = {
  // List of files to be processed.
  apis: ['./routes/products.js'],
  // You can also set globs for your apis
  // e.g. './routes/*.js'
  basePath: '/',
  swaggerDefinition: {
    info: {
      description: 'Products API with autogenerated swagger doc',
      swagger: '2.0',
      title: 'Inventory API',
      version: '1.0.0',
    },
  },
};
const specs = swaggerJsdoc(options);

module.exports = specs;